# Generated by Django 2.2 on 2019-05-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20190507_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='users_avatars'),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('W', 'Female')], max_length=1, verbose_name='sex'),
        ),
    ]
